In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [2]:
print(a + a)

[2 4 6 8]


In [4]:
b = [1, 2, 3, 4]
print(b + b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [5]:
a = np.array([[[1, 2], [3, 4]], [[1, 2], [3, 4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [6]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]
