In [48]:
import numpy as np

A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3')
x = np.matrix('1;2;3;4')
print(A)
print(x)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1]
 [2]
 [3]
 [4]]


In [49]:
print(A.shape)
print(x.shape)
b=A*x
print("A*x=", b)

(4, 4)
(4, 1)
A*x= [[15]
 [19]
 [26]
 [44]]


In [50]:
A=np.array([\
           [1, 4, 2, 0],\
           [9, 5, 0, 0],\
           [4, 0, 2, 4],\
           [6, 1, 8, 3]])
x = np.array([1, 2, 3, 4]).reshape(1, -1)

In [51]:
print(A)
print(x)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1 2 3 4]]


In [53]:
print(A.shape)
print(x.T.shape)
b = A@x.T

print(b)

(4, 4)
(4, 1)
[[15]
 [19]
 [26]
 [44]]


In [54]:
A=np.array([\
           [4, 5, 2, 1],\
           [2, 3, 8, 0],\
           [1, 0, 7, 2]])
x = np.array([[1], [2], [3], [4]])

In [55]:
print(A)
print(x)

[[4 5 2 1]
 [2 3 8 0]
 [1 0 7 2]]
[[1]
 [2]
 [3]
 [4]]


In [60]:
print(A.shape)
print(x.shape)

b = A@x
print(b)

(3, 4)
(4, 1)
[[24]
 [32]
 [30]]
