In [2]:
import numpy as np
A = np.matrix('\
1, 4, 2, 0;\
9, 5, 0, 0;\
4, 0, 2, 4;\
6, 1, 8, 3')
x = np.matrix('1,2,3,4')
print(A)
print(x)
b=A*x.T
print("A*x=",b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1 2 3 4]]
A*x= [[15]
 [19]
 [26]
 [44]]


In [10]:
A = np.array([\
             [1, 4, 2, 0],\
             [9, 5, 0, 0],\
             [4, 0, 2, 4],\
             [6, 1, 8, 3]])
x = np.array([1,2,3,4]).reshape(1,-1)
print("A*x=",A*x)

A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]


In [13]:
A = np.matrix('\
             4, 5, 2, 1;\
             2, 3, 8, 0;\
             1, 0, 7, 2')
x = np.matrix('1,2,3,4')
print("A*x=",A*x.T)

A*x= [[24]
 [32]
 [30]]
