In [3]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(b)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [4]:
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [15]:
a = np.array([[1],[2],[3],[4]])
print(a)
print(a.T)
print(a.T.reshape(-1,4))
print(a.shape)
print(a.T.reshape(-1,4).T.shape)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1 2 3 4]]
(4, 1)
(4, 1)


In [17]:
a = np.array([1,2,3,4])
b = a.reshape(4,-1)
print(a.reshape(4,-1))
print(a.shape,",",b.shape)

[[1]
 [2]
 [3]
 [4]]
(4,) , (4, 1)


In [18]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
print(a.reshape(3,-1))
print(a.shape)
print(a.reshape(-1,2))
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(6,)


In [19]:
a = np.array([10,20,30,40,50,60])
print(a)
b = a[[4,2,0]]
print(b)

[10 20 30 40 50 60]
[50 30 10]


In [20]:
idx = np.arange(0, len(a))
print(idx)
np.random.shuffle(idx)
print(idx)
print(a[idx])

[0 1 2 3 4 5]
[0 2 4 5 1 3]
[10 30 50 60 20 40]
